### ISSUE TITLE
Incompatibilty with rollbar>=0.15.0

### ISSUE THREAD

**Issue by FranciscoNMora** [danielwelch/django-q-rollbar#2]
When installing django-q-rollbar, it installs rollbar-0.14.7, and uninstalls any higher version. Current version of rollbar is 0.16.1, and 0.14.7 will be soon deprecated.

Collecting rollbar<0.15.0,>=0.14.0
  Using cached rollbar-0.14.7-py3-none-any.whl
Requirement already satisfied: six>=1.9.0 in ./venv/lib/python3.9/site-packages (from rollbar<0.15.0,>=0.14.0->django-q-rollbar) (1.16.0)
Requirement already satisfied: requests>=0.12.1 in ./venv/lib/python3.9/site-packages (from rollbar<0.15.0,>=0.14.0->django-q-rollbar) (2.25.1)
Requirement already satisfied: idna<3,>=2.5 in ./venv/lib/python3.9/site-packages (from requests>=0.12.1->rollbar<0.15.0,>=0.14.0->django-q-rollbar) (2.10)
Requirement already satisfied: certifi>=2017.4.17 in ./venv/lib/python3.9/site-packages (from requests>=0.12.1->rollbar<0.15.0,>=0.14.0->django-q-rollbar) (2021.5.30)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in ./venv/lib/python3.9/site-packages (from requests>=0.12.1->rollbar<0.15.0,>=0.14.0->django-q-rollbar) (1.26.5)
Requirement already satisfied: chardet<5,>=3.0.2 in ./venv/lib/python3.9/site-packages (from requests>=0.12.1->rollbar<0.15.0,>=0.14.0->django-q-rollbar) (4.0.0)
Installing collected packages: rollbar
  Attempting uninstall: rollbar
    Found existing installation: rollbar 0.16.1
    Uninstalling rollbar-0.16.1:
      Successfully uninstalled rollbar-0.16.1
Successfully installed rollbar-0.14.7

**Comment by c-goosen** [comment]
Just merged changes to allow higher versions of rollbar, from a PR.

**Comment by theunraveler** [comment]
@c-goosen : could release a new version to PyPI with this change included? Thanks!
